.\" Manpage for iTMSTransporter.
.TH man 1 "01 Nov 2023" "version 3.3.0.8" "iTMSTransporter - iTunes Store Transporter"
.SH NAME
iTMSTransporter \- deliver content to iTunes, the App Store, and Apple Books.
.SH SYNOPSIS
.B iTMSTransporter 
[\fB\-help\fR \fi<mode>\fR | \fB\-info\fR | \fB-m\fR <mode> | \fB-version\fR]
.SH DESCRIPTION
See the user's guide at: https://help.apple.com/itc/transporteruserguide
.SH OPTIONS
.TP
.BR \-help " " \fi<mode>\fR
Requests the help for the specified \fi<mode>\fR. If \fi<mode>\fR is not specified, general help is displayed.
.TP
.BR \-info
Displays the copyright notice and acknowledgements.
.TP
\fB-m\fR <mode>
Runs iTMSTransporter in <mode>, see user's guide for more details.
.TP
.BR \-version
Displays the version information.
.SH SEE ALSO
altool(1)
.SH BUGS
To report bugs go to: https://bugreport.apple.com
